import type { StackGroup } from '@/@types/stack.types';

const STACK_GROUPS: StackGroup[] = [
  {
    titleKey: 'stack.main',
    cols: 'md:grid-cols-5',
    items: [
      {
        url: '/StackIcons/next.svg',
        tooltip: 'Next.js',
        border: 'border-white',
        text: 'text-white',
        bg: 'bg-white/10',
        hover: 'hover-glow-white',
      },
      {
        url: '/StackIcons/react.svg',
        tooltip: 'React',
        border: 'border-cyan-300',
        text: 'text-cyan-300',
        bg: 'bg-cyan-300/10',
        hover: 'hover-glow-cyan',
      },
      {
        url: '/StackIcons/ts.svg',
        tooltip: 'Typescript',
        border: 'border-blue-500',
        text: 'text-blue-500',
        bg: 'bg-blue-500/10',
        hover: 'hover-glow-blue',
      },
      {
        url: '/StackIcons/js.svg',
        tooltip: 'Javascript',
        border: 'border-amber-500',
        text: 'text-amber-500',
        bg: 'bg-amber-500/10',
        hover: 'hover-glow-amber',
      },
      {
        url: '/StackIcons/tailwind.svg',
        tooltip: 'Tailwind',
        border: 'border-sky-400',
        text: 'text-sky-400',
        bg: 'bg-sky-400/10',
        hover: 'hover-glow-sky',
      },
    ],
  },
  {
    titleKey: 'stack.also',
    cols: 'md:grid-cols-5',
    items: [
      {
        url: '/StackIcons/nodejs.svg',
        tooltip: 'Node.js',
        border: 'border-green-500',
        text: 'text-green-500',
        bg: 'bg-green-500/10',
        hover: 'hover-glow-green',
      },
      {
        url: '/StackIcons/jwt.svg',
        tooltip: 'JWT',
        border: 'border-amber-500',
        text: 'text-amber-500',
        bg: 'bg-amber-500/10',
        hover: 'hover-glow-amber',
      },
      {
        url: '/StackIcons/zod.svg',
        tooltip: 'Zod',
        border: 'border-blue-400',
        text: 'text-blue-400',
        bg: 'bg-blue-400/10',
        hover: 'hover-glow-blue',
      },
      {
        url: '/StackIcons/tanstack.svg',
        tooltip: 'TanStack Query',
        border: 'border-green-500',
        text: 'text-green-500',
        bg: 'bg-green-500/10',
        hover: 'hover-glow-green',
      },
      {
        url: '/StackIcons/shopify.svg',
        tooltip: 'Shopify API',
        border: 'border-emerald-400',
        text: 'text-emerald-400',
        bg: 'bg-emerald-400/10',
        hover: 'hover-glow-lime',
      },
    ],
  },
  {
    titleKey: 'stack.database',
    cols: 'md:grid-cols-4',
    items: [
      {
        url: '/StackIcons/mongo.svg',
        tooltip: 'MongoDB',
        border: 'border-green-400',
        text: 'text-green-400',
        bg: 'bg-green-400/10',
        hover: 'hover-glow-green',
      },
      {
        url: '/StackIcons/mongoose.svg',
        tooltip: 'Mongoose',
        border: 'border-red-400',
        text: 'text-red-400',
        bg: 'bg-red-400/10',
        hover: 'hover-glow-red',
      },
      {
        url: '/StackIcons/blob.svg',
        tooltip: 'Vercel BLOB',
        border: 'border-yellow-400',
        text: 'text-yellow-400',
        bg: 'bg-yellow-400/10',
        hover: 'hover-glow-yellow',
      },
      {
        url: '/StackIcons/firebase.svg',
        tooltip: 'Firebase',
        border: 'border-yellow-400',
        text: 'text-yellow-400',
        bg: 'bg-yellow-400/10',
        hover: 'hover-glow-yellow',
      },
    ],
  },
  {
    titleKey: 'stack.tools',
    items: [
      {
        url: '/StackIcons/astro.png',
        tooltip: 'Astro',
        border: 'border-purple-400',
        text: 'text-purple-400',
        bg: 'bg-purple-400/10',
        hover: 'hover-glow-purple',
      },
      {
        url: '/StackIcons/vite.png',
        tooltip: 'Vite',
        border: 'border-purple-400',
        text: 'text-purple-400',
        bg: 'bg-purple-400/10',
        hover: 'hover-glow-purple',
      },
      {
        url: '/StackIcons/firebase.png',
        tooltip: 'Firebase',
        border: 'border-amber-500',
        text: 'text-amber-500',
        bg: 'bg-amber-500/10',
        hover: 'hover-glow-amber',
      },
      {
        url: '/StackIcons/shopify.svg',
        tooltip: 'Shopify',
        border: 'border-emerald-400',
        text: 'text-emerald-400',
        bg: 'bg-emerald-400/10',
        hover: 'hover-glow-lime',
      },
      {
        url: '/StackIcons/postman.svg',
        tooltip: 'Postman',
        border: 'border-orange-400',
        text: 'text-orange-400',
        bg: 'bg-orange-400/10',
        hover: 'hover-glow-orange',
      },
      {
        url: '/StackIcons/i18.svg',
        tooltip: 'i18Next',
        border: 'border-lime-400',
        text: 'text-lime-400',
        bg: 'bg-lime-400/10',
        hover: 'hover-glow-lime',
      },
      {
        url: '/StackIcons/figma.png',
        tooltip: 'Figma',
        border: 'border-pink-500',
        text: 'text-pink-500',
        bg: 'bg-pink-500/10',
        hover: 'hover-glow-pink',
      },
      {
        url: '/StackIcons/FramerMotion.svg',
        tooltip: 'Framer Motion',
        border: 'border-purple-400',
        text: 'text-purple-400',
        bg: 'bg-purple-400/10',
        hover: 'hover-glow-purple',
      },
      {
        url: '/StackIcons/Shadcn-UI.svg',
        tooltip: 'Shadcn/UI',
        border: 'border-white',
        text: 'text-white',
        bg: 'bg-white/10',
        hover: 'hover-glow-white scale-110',
      },
      {
        url: '/StackIcons/prettier.png',
        tooltip: 'Prettier',
        border: 'border-indigo-400',
        text: 'text-indigo-400',
        bg: 'bg-indigo-400/10',
        hover: 'hover-glow-indigo',
      },
      {
        url: '/StackIcons/git.png',
        tooltip: 'Git',
        border: 'border-orange-600',
        text: 'text-orange-600',
        bg: 'bg-orange-600/10',
        hover: 'hover-glow-orange',
      },
      {
        url: '/StackIcons/github.svg',
        tooltip: 'GitHub',
        border: 'border-neutral-500',
        text: 'text-neutral-200',
        bg: 'bg-neutral-500/10',
        hover: 'hover-glow-white',
      },
      {
        url: '/StackIcons/linux.png',
        tooltip: 'Linux',
        border: 'border-yellow-500',
        text: 'text-yellow-500',
        bg: 'bg-yellow-500/10',
        hover: 'hover-glow-yellow',
      },
      {
        url: '/StackIcons/npm.png',
        tooltip: 'NPM',
        border: 'border-red-500',
        text: 'text-red-500',
        bg: 'bg-red-500/10',
        hover: 'hover-glow-red',
      },
      {
        url: '/StackIcons/vercel.svg',
        tooltip: 'Vercel',
        border: 'border-neutral-400',
        text: 'text-neutral-300',
        bg: 'bg-neutral-500/10',
        hover: 'hover-glow-white',
      },
    ],
  },
];
export { STACK_GROUPS };
